Logger replacement with Boost.Log2
NilFoundation/zkllvm-assigner pull request #115
Opened 2023-09-09 18:00 UTC by nemothenoone

Resolves #111

2023-09-12 18:58 UTC, nkaskov commented
All the merge commits have to be replaced with rebases in order to keep the commit history clean.

2023-09-12 18:59 UTC, nkaskov requested changes
All the merge commits have to be replaced with rebases in order to keep the commit history clean. Otherwise we have to much to review if something goes wrong.

2023-09-17 10:07 UTC, nemothenoone commented
> We need to have a simple way to change logger level without changing logger's code.

There is a way to do this by interacting with Boost.Log2 core as the manual states explicitly in the second chapter:
https://www.boost.org/doc/libs/1_83_0/libs/log/doc/html/log/tutorial/trivial_filtering.html

2023-09-19 13:36 UTC, nemothenoone commented on include/nil/blueprint/asserts.hpp
> +#define BOOST_UNREACHABLE_MSG(msg) BOOST_VERIFY_MSG(false, "UNREACHABLE: "(msg))
Hm. Not merging this in then. Will come back with some solution.

2023-11-22 12:44 UTC, nkaskov commented
Logger functionality separated from asserts and moved to another PR: https://github.com/NilFoundation/zkllvm-assigner/pull/154

2023-11-22 12:44 UTC, closed without merging