initial circuit size estimation added
NilFoundation/zkllvm-assigner pull request #174
Opened 2024-01-17 18:54 UTC by CblPOK-git

2024-01-22 07:29 UTC, akokoshn commented on include/nil/blueprint/handle_component.hpp
> +        std::map<std::string, int> components_frequency;
1. I suggest use map<sting, statistic>
```
struct statistic {
int components_frequency;
int rows_used;
int gates_used
}
```
2. Global variable may be not better design solution. I guggest to keep map in parser instance and pass as reference.

2024-01-22 07:29 UTC, akokoshn commented on include/nil/blueprint/handle_component.hpp
> +        std::map<std::string, int> rows_per_component;
what is different `rows_used` vs `rows_per_component`?

2024-02-14 09:04 UTC, akokoshn requested changes

2024-02-14 09:04 UTC, akokoshn commented on include/nil/blueprint/statistics.hpp
> +                component_counter[name] += 1;
`if (find(name) != end) {set counter  = 1, rows, withness, ...,} else {update counter}`

2024-02-14 09:04 UTC, akokoshn commented on include/nil/blueprint/statistics.hpp
> +                std::cout << "\n=====================================================================================\n";
looks not so good in small console (takes few lines), may be short delimiter enough `\b====\n`

2024-02-14 17:00 UTC, makxenov approved these changes

2024-02-14 20:30 UTC, akokoshn requested changes

2024-02-14 20:30 UTC, akokoshn commented on include/nil/blueprint/statistics.hpp
> +        nil::blueprint::component_calls statistics;
global variable is not so good solution, can we keep `statistics` as member of `parser` and pass by reference like `assignment table`?

2024-02-15 09:34 UTC, akokoshn approved these changes

2024-02-15 11:43 UTC, merged