59 non native parsing json
NilFoundation/zkllvm-assigner pull request #67
Opened 2023-06-29 09:23 UTC by CblPOK-git

2023-07-03 08:33 UTC, makxenov requested changes

2023-07-03 08:33 UTC, makxenov commented on include/nil/blueprint/public_input.hpp
> +                assert((value.at("curve").as_array().size() == 2) && "curve element consists of two field elements!");
Replace with `ASSERT_MSG`

2023-07-03 11:27 UTC, makxenov approved these changes

2023-07-04 09:59 UTC, nkaskov approved these changes

2023-07-04 10:02 UTC, merged